// src/components/DataTable/DataTable.tsx
import { useState, useEffect } from 'react';
import DataToolbar from '../DataToolbar/DataToolbar';
import { DatatableHeader } from '../DatatableHeader/DatatableHeader';
import type { DatatableHeaderColumn, SortDirection } from '../DatatableHeader/DatatableHeader';
import { DatatableSelectCell } from '../DatatableSelectCell/DatatableSelectCell';

// ── Types ────────────────────────────────────────────────────────────────────

export type { SortDirection };

export type DataTableColumn<T = Record<string, unknown>> = {
  key: string;
  header: string;
  sortable?: boolean;
  render?: (value: unknown, row: T) => React.ReactNode;
};

export type DataTableProps<T = Record<string, unknown>> = {
  columns: DataTableColumn<T>[];
  data: T[];
  perPage?: number;
  showToolbar?: boolean;
  showPagination?: boolean;
  selectable?: boolean;
  className?: string;
};

// ── Pagination icons ─────────────────────────────────────────────────────────

function IcChevronLeft() {
  return (
    <svg width="20" height="20" viewBox="0 0 20 20" fill="none" aria-hidden="true">
      <path d="M12.5 15L7.5 10L12.5 5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}

function IcChevronRight() {
  return (
    <svg width="20" height="20" viewBox="0 0 20 20" fill="none" aria-hidden="true">
      <path d="M7.5 15L12.5 10L7.5 5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}

function IcChevronDoubleLeft() {
  return (
    <svg width="20" height="20" viewBox="0 0 20 20" fill="none" aria-hidden="true">
      <path d="M11 15L6 10L11 5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
      <path d="M15 15L10 10L15 5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}

function IcChevronDoubleRight() {
  return (
    <svg width="20" height="20" viewBox="0 0 20 20" fill="none" aria-hidden="true">
      <path d="M5 15L10 10L5 5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
      <path d="M9 15L14 10L9 5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}

// ── Pagination ───────────────────────────────────────────────────────────────

function getVisiblePages(current: number, total: number): number[] {
  const maxVisible = 5;
  if (total <= maxVisible) return Array.from({ length: total }, (_, i) => i + 1);

  let start = current - Math.floor(maxVisible / 2);
  let end = start + maxVisible - 1;

  if (start < 1) { start = 1; end = maxVisible; }
  if (end > total) { end = total; start = total - maxVisible + 1; }

  return Array.from({ length: end - start + 1 }, (_, i) => start + i);
}

function Pagination({
  currentPage,
  totalPages,
  onPageChange,
}: {
  currentPage: number;
  totalPages: number;
  onPageChange: (page: number) => void;
}) {
  const [inputValue, setInputValue] = useState(String(currentPage));
  const pages = getVisiblePages(currentPage, totalPages);

  function handleInputSubmit(e: React.KeyboardEvent) {
    if (e.key === 'Enter') {
      const page = parseInt(inputValue, 10);
      if (page >= 1 && page <= totalPages) onPageChange(page);
    }
  }

  return (
    <nav aria-label="Pagination" className="flex items-center justify-center gap-3">
      <div className="flex items-start">
        <button
          type="button"
          aria-label="First page"
          disabled={currentPage === 1}
          onClick={() => onPageChange(1)}
          className="flex size-9 items-center justify-center rounded-circle text-element-primary disabled:text-element-disabled
            hover:bg-interaction-neutral-hover active:bg-interaction-neutral-pressed
            focus-visible:outline-none focus-visible:shadow-focus-button-ring"
        >
          <IcChevronDoubleLeft />
        </button>
        <button
          type="button"
          aria-label="Previous page"
          disabled={currentPage === 1}
          onClick={() => onPageChange(currentPage - 1)}
          className="flex size-9 items-center justify-center rounded-circle text-element-primary disabled:text-element-disabled
            hover:bg-interaction-neutral-hover active:bg-interaction-neutral-pressed
            focus-visible:outline-none focus-visible:shadow-focus-button-ring"
        >
          <IcChevronLeft />
        </button>

        <div className="flex items-center">
          {pages.map((p) => (
            <button
              key={p}
              type="button"
              aria-current={p === currentPage ? 'page' : undefined}
              onClick={() => onPageChange(p)}
              className={`relative flex size-9 flex-col items-center justify-center text-text-sm leading-text-sm
                hover:bg-interaction-neutral-hover active:bg-interaction-neutral-pressed
                focus-visible:outline-none focus-visible:shadow-focus-button-ring ${
                  p === currentPage
                    ? 'font-semibold text-element-brand'
                    : 'font-regular text-element-quaternary'
                }`}
            >
              {p}
              {p === currentPage && (
                <span className="absolute bottom-0 left-3 right-3 h-[3px] rounded-1 bg-element-brand" />
              )}
            </button>
          ))}
        </div>

        <button
          type="button"
          aria-label="Next page"
          disabled={currentPage === totalPages}
          onClick={() => onPageChange(currentPage + 1)}
          className="flex size-9 items-center justify-center rounded-circle text-element-primary disabled:text-element-disabled
            hover:bg-interaction-neutral-hover active:bg-interaction-neutral-pressed
            focus-visible:outline-none focus-visible:shadow-focus-button-ring"
        >
          <IcChevronRight />
        </button>
        <button
          type="button"
          aria-label="Last page"
          disabled={currentPage === totalPages}
          onClick={() => onPageChange(totalPages)}
          className="flex size-9 items-center justify-center rounded-circle text-element-primary disabled:text-element-disabled
            hover:bg-interaction-neutral-hover active:bg-interaction-neutral-pressed
            focus-visible:outline-none focus-visible:shadow-focus-button-ring"
        >
          <IcChevronDoubleRight />
        </button>
      </div>

      <div className="flex items-center gap-2">
        <input
          type="text"
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
          onKeyDown={handleInputSubmit}
          aria-label="Go to page"
          className="h-[30px] w-[34px] rounded-4 border border-border-normal bg-surface-container px-2.5 py-2 text-center text-text-xs leading-text-xs font-regular text-element-quaternary outline-none
            focus:shadow-[0_0_0_2px_var(--color-primary)]"
        />
        <span className="text-text-sm leading-text-sm font-regular text-element-quaternary">
          of {totalPages} page
        </span>
      </div>
    </nav>
  );
}

// ── DataTable ────────────────────────────────────────────────────────────────

export default function DataTable<T extends Record<string, unknown>>({
  columns,
  data,
  perPage: initialPerPage = 10,
  showToolbar = true,
  showPagination = true,
  selectable = false,
  className,
}: DataTableProps<T>) {
  const [currentPage, setCurrentPage] = useState(1);
  const [perPage, setPerPage] = useState(initialPerPage);
  const [sortKey, setSortKey] = useState<string | null>(null);
  const [sortDir, setSortDir] = useState<SortDirection | null>(null);
  const [selectedRows, setSelectedRows] = useState<Set<number>>(new Set());
  const [visibleColumnHeaders, setVisibleColumnHeaders] = useState<string[]>(
    () => columns.map((c) => c.header),
  );

  useEffect(() => {
    setPerPage(initialPerPage);
    setCurrentPage(1);
  }, [initialPerPage]);

  const visibleCols = columns.filter((c) => visibleColumnHeaders.includes(c.header));

  const headerColumns: DatatableHeaderColumn[] = visibleCols.map((col) => ({
    key: col.key,
    label: col.header,
    icon: col.sortable !== false ? 'sort' : 'none',
  }));

  function handleSortChange(key: string, direction: SortDirection) {
    setSortKey(key);
    setSortDir(direction);
    setCurrentPage(1);
  }

  function handlePerPageChange(value: number) {
    setPerPage(value);
    setCurrentPage(1);
  }

  const sorted = sortKey && sortDir
    ? [...data].sort((a, b) => {
        const av = String(a[sortKey] ?? '');
        const bv = String(b[sortKey] ?? '');
        const cmp = av.localeCompare(bv);
        return sortDir === 'desc' ? -cmp : cmp;
      })
    : data;

  const totalPages = Math.max(1, Math.ceil(data.length / perPage));
  const pageData = sorted.slice((currentPage - 1) * perPage, currentPage * perPage);

  const allPageSelected =
    selectable &&
    pageData.length > 0 &&
    pageData.every((_, i) => selectedRows.has((currentPage - 1) * perPage + i));
  const somePageSelected =
    selectable &&
    !allPageSelected &&
    pageData.some((_, i) => selectedRows.has((currentPage - 1) * perPage + i));

  function handleSelectAll(checked: boolean) {
    setSelectedRows((prev) => {
      const next = new Set(prev);
      pageData.forEach((_, i) => {
        const idx = (currentPage - 1) * perPage + i;
        if (checked) next.add(idx);
        else next.delete(idx);
      });
      return next;
    });
  }

  function handleSelectRow(absoluteIdx: number, checked: boolean) {
    setSelectedRows((prev) => {
      const next = new Set(prev);
      if (checked) next.add(absoluteIdx);
      else next.delete(absoluteIdx);
      return next;
    });
  }

  return (
    <div className={`flex flex-col gap-5 overflow-hidden text-left ${className ?? ''}`}>
      <div className="overflow-hidden rounded-4 border border-border-solid-variant bg-surface-container">
        {showToolbar && (
          <DataToolbar
            totalCount={data.length}
            perPage={perPage}
            perPageOptions={[10, 20, 50, 100]}
            onPerPageChange={handlePerPageChange}
            columns={columns.map((c) => c.header)}
            visibleColumns={visibleColumnHeaders}
            onVisibleColumnsChange={(cols) => { setVisibleColumnHeaders(cols); setCurrentPage(1); }}
          />
        )}

        <DatatableHeader
          columns={headerColumns}
          showSelect={selectable}
          selectChecked={allPageSelected}
          selectIndeterminate={somePageSelected}
          onSelectChange={handleSelectAll}
          onSortChange={handleSortChange}
        />

        <div>
          {pageData.map((row, rowIdx) => {
            const absoluteIdx = (currentPage - 1) * perPage + rowIdx;
            const isSelected = selectable && selectedRows.has(absoluteIdx);
            return (
              <div
                key={rowIdx}
                className={`flex items-center border-b border-border-solid-variant last:border-b-0
                  hover:bg-interaction-neutral-hover
                  ${isSelected ? 'bg-selected-container-variant' : ''}`}
              >
                {selectable && (
                  <DatatableSelectCell
                    size="lg"
                    checked={isSelected}
                    onChange={(checked) => handleSelectRow(absoluteIdx, checked)}
                    aria-label={`Select row ${absoluteIdx + 1}`}
                  />
                )}
                <div className="flex min-w-0 flex-1">
                  {visibleCols.map((col) => (
                    <div key={col.key} className="flex min-h-9 min-w-0 flex-1 items-center py-3">
                      <div className="w-2 shrink-0" />
                      <span className="min-w-0 flex-1 truncate text-text-md leading-text-md font-regular text-element-secondary">
                        {col.render ? col.render(row[col.key], row) : String(row[col.key] ?? '')}
                      </span>
                      <div className="w-2 shrink-0" />
                    </div>
                  ))}
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {showPagination && totalPages > 1 && (
        <Pagination
          currentPage={currentPage}
          totalPages={totalPages}
          onPageChange={(page) => setCurrentPage(Math.max(1, Math.min(page, totalPages)))}
        />
      )}
    </div>
  );
}

// src-vue/components/DataTable/DataTable.vue
<!--
  DataTable — 정렬/페이지네이션/컬럼 토글/행 선택을 지원하는 데이터 테이블

  React: src/components/DataTable/DataTable.tsx

  ── 제네릭 단순화 ────────────────────────────────────────────────────────────
  React 원본은 `DataTable<T extends Record<string, unknown>>`로 제네릭이었다.
  이 코드베이스에는 아직 `<script setup generic="...">` 패턴 선례가 없고, 이
  컴포넌트가 Storybook 데모 용도로 쓰이는 한 제네릭 타입 안정성의 실익이 크지
  않다고 판단해 `Record<string, unknown>` 고정 타입으로 단순화했다. 필요해지면
  Vue 3.5의 `generic` 속성으로 나중에 승격 가능.

  ── render prop 이식 ─────────────────────────────────────────────────────────
  React의 `render?: (value, row) => ReactNode`를 Vue 템플릿에서 그대로 쓰기
  위해 `<component :is="() => col.render(...)" />` 패턴(함수를 함수형 컴포넌트로
  취급하는 Vue 3 트릭)을 사용했다. 문자열과 VNode 반환 모두 지원된다.

  ── Pagination ───────────────────────────────────────────────────────────────
  DataTable 전용 내부 Pagination은 ./DataTablePagination.vue로 분리했다 (React
  원본에서도 파일 내부 전용 함수였고, DatatableTree의 것과 클래스/알고리즘이
  거의 동일하지만 원본 자체가 공유하지 않으므로 포팅 시에도 공유하지 않았다 —
  DataTablePagination.vue 상단 주석 참고).

  ── DatatableHeader / DatatableSelectCell 연동 ──────────────────────────────
  다른 에이전트가 포팅한 실제 Vue 버전을 확인해 prop 이름을 그대로 맞췄다:
  DatatableHeader는 `class-name`(className, `class`가 아님) prop과 `selectChange`
  /`sortChange` emit을 쓴다. DatatableSelectCell은 `ariaLabel` prop과 `change`
  emit(boolean)을 쓴다.
-->
<script lang="ts">
import type { SortDirection } from '../DatatableHeader/DatatableHeader.vue';

export type { SortDirection };

export type DataTableColumn = {
  key: string;
  header: string;
  sortable?: boolean;
  render?: (value: unknown, row: Record<string, unknown>) => unknown;
};
</script>

<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import DataToolbar from '../DataToolbar/DataToolbar.vue';
import DatatableHeader from '../DatatableHeader/DatatableHeader.vue';
import type { DatatableHeaderColumn } from '../DatatableHeader/DatatableHeader.vue';
import DatatableSelectCell from '../DatatableSelectCell/DatatableSelectCell.vue';
import DataTablePagination from './DataTablePagination.vue';
// NOTE: SortDirection / DataTableColumn are declared in the plain <script> block
// above and are available here — Vue SFCs share module scope across <script> and
// <script setup> (this codebase's established convention for type exports, see
// IconButton.vue / Select.vue / DatatableHeader.vue).

const props = withDefaults(
  defineProps<{
    columns: DataTableColumn[];
    data: Record<string, unknown>[];
    perPage?: number;
    showToolbar?: boolean;
    showPagination?: boolean;
    selectable?: boolean;
    class?: string;
  }>(),
  {
    perPage: 10,
    showToolbar: true,
    showPagination: true,
    selectable: false,
    class: '',
  },
);

// ── State ────────────────────────────────────────────────────────────────

const currentPage = ref(1);
const perPageState = ref(props.perPage);
const sortKey = ref<string | null>(null);
const sortDir = ref<SortDirection | null>(null);
const selectedRows = ref<Set<number>>(new Set());
const visibleColumnHeaders = ref<string[]>(props.columns.map((c) => c.header));

// React 원본의 `useEffect(() => { setPerPage(initialPerPage); setCurrentPage(1) }, [initialPerPage])`
// 를 미러링: perPage prop이 나중에 바뀌면 내부 상태를 재시드한다.
watch(
  () => props.perPage,
  (next) => {
    perPageState.value = next;
    currentPage.value = 1;
  },
);

// ── Derived ──────────────────────────────────────────────────────────────

const visibleCols = computed(() =>
  props.columns.filter((c) => visibleColumnHeaders.value.includes(c.header)),
);

const headerColumns = computed<DatatableHeaderColumn[]>(() =>
  visibleCols.value.map((col) => ({
    key: col.key,
    label: col.header,
    icon: col.sortable !== false ? 'sort' : 'none',
  })),
);

const sorted = computed(() => {
  if (!sortKey.value || !sortDir.value) return props.data;
  const key = sortKey.value;
  const dir = sortDir.value;
  return [...props.data].sort((a, b) => {
    const av = String(a[key] ?? '');
    const bv = String(b[key] ?? '');
    const cmp = av.localeCompare(bv);
    return dir === 'desc' ? -cmp : cmp;
  });
});

const totalPages = computed(() => Math.max(1, Math.ceil(props.data.length / perPageState.value)));

const pageData = computed(() =>
  sorted.value.slice(
    (currentPage.value - 1) * perPageState.value,
    currentPage.value * perPageState.value,
  ),
);

const allPageSelected = computed(
  () =>
    props.selectable &&
    pageData.value.length > 0 &&
    pageData.value.every((_, i) =>
      selectedRows.value.has((currentPage.value - 1) * perPageState.value + i),
    ),
);

const somePageSelected = computed(
  () =>
    props.selectable &&
    !allPageSelected.value &&
    pageData.value.some((_, i) =>
      selectedRows.value.has((currentPage.value - 1) * perPageState.value + i),
    ),
);

// ── Handlers ─────────────────────────────────────────────────────────────

function handleSortChange(key: string, direction: SortDirection) {
  sortKey.value = key;
  sortDir.value = direction;
  currentPage.value = 1;
}

function handlePerPageChange(value: number) {
  perPageState.value = value;
  currentPage.value = 1;
}

function handleVisibleColumnsChange(cols: string[]) {
  visibleColumnHeaders.value = cols;
  currentPage.value = 1;
}

function handleSelectAll(checked: boolean) {
  const next = new Set(selectedRows.value);
  pageData.value.forEach((_, i) => {
    const idx = (currentPage.value - 1) * perPageState.value + i;
    if (checked) next.add(idx);
    else next.delete(idx);
  });
  selectedRows.value = next;
}

function handleSelectRow(absoluteIdx: number, checked: boolean) {
  const next = new Set(selectedRows.value);
  if (checked) next.add(absoluteIdx);
  else next.delete(absoluteIdx);
  selectedRows.value = next;
}

function handlePageChange(page: number) {
  currentPage.value = Math.max(1, Math.min(page, totalPages.value));
}

function isRowSelected(absoluteIdx: number) {
  return props.selectable && selectedRows.value.has(absoluteIdx);
}

// `render` prop 포팅: React의 `render?: (value, row) => ReactNode`를 Vue에서
// 그대로 쓰기 위해 함수를 함수형 컴포넌트로 취급하는 `<component :is="fn" />`
// 트릭을 쓴다 (문자열/VNode 반환 모두 지원). optional chaining으로 non-null
// assertion 없이 안전하게 처리한다.
function cellRenderFn(col: DataTableColumn, row: Record<string, unknown>) {
  return () => col.render?.(row[col.key], row);
}
</script>

<template>
  <div :class="`flex flex-col gap-5 overflow-hidden text-left ${props.class}`">
    <div class="overflow-hidden rounded-4 border border-border-solid-variant bg-surface-container">
      <DataToolbar
        v-if="showToolbar"
        :total-count="data.length"
        :per-page="perPageState"
        :per-page-options="[10, 20, 50, 100]"
        :columns="columns.map((c) => c.header)"
        :visible-columns="visibleColumnHeaders"
        @per-page-change="handlePerPageChange"
        @visible-columns-change="handleVisibleColumnsChange"
      />

      <DatatableHeader
        :columns="headerColumns"
        :show-select="selectable"
        :select-checked="allPageSelected"
        :select-indeterminate="somePageSelected"
        @select-change="handleSelectAll"
        @sort-change="handleSortChange"
      />

      <div>
        <div
          v-for="(row, rowIdx) in pageData"
          :key="rowIdx"
          :class="[
            'flex items-center border-b border-border-solid-variant last:border-b-0',
            'hover:bg-interaction-neutral-hover',
            isRowSelected((currentPage - 1) * perPageState + rowIdx) ? 'bg-selected-container-variant' : '',
          ]"
        >
          <DatatableSelectCell
            v-if="selectable"
            size="lg"
            :checked="isRowSelected((currentPage - 1) * perPageState + rowIdx)"
            :aria-label="`Select row ${(currentPage - 1) * perPageState + rowIdx + 1}`"
            @change="(checked) => handleSelectRow((currentPage - 1) * perPageState + rowIdx, checked)"
          />
          <div class="flex min-w-0 flex-1">
            <div v-for="col in visibleCols" :key="col.key" class="flex min-h-9 min-w-0 flex-1 items-center py-3">
              <div class="w-2 shrink-0" />
              <span class="min-w-0 flex-1 truncate text-text-md leading-text-md font-regular text-element-secondary text-left">
                <component v-if="col.render" :is="cellRenderFn(col, row)" />
                <template v-else>{{ String(row[col.key] ?? '') }}</template>
              </span>
              <div class="w-2 shrink-0" />
            </div>
          </div>
        </div>
      </div>
    </div>

    <DataTablePagination
      v-if="showPagination && totalPages > 1"
      :current-page="currentPage"
      :total-pages="totalPages"
      @change="handlePageChange"
    />
  </div>
</template>
