// src-vue/components/Sidesheet/Sidesheet.vue
<script lang="ts">
import type { OverlayHeaderModalSize } from '../Modal/OverlayHeaderModal.vue';

export type SidesheetSize = 'sm' | 'md';
</script>

<script setup lang="ts">
import { computed } from 'vue';
import OverlayHeaderModal from '../Modal/OverlayHeaderModal.vue';
import OverlayFooterModal from '../Modal/OverlayFooterModal.vue';

const SIZE_WIDTH: Record<SidesheetSize, number> = {
  sm: 360,
  md: 480,
};

const SIZE_HEADER: Record<SidesheetSize, OverlayHeaderModalSize> = {
  sm: 'sm',
  md: 'md',
};

const props = withDefaults(
  defineProps<{
    size?: SidesheetSize;
    showFooter?: boolean;
    cancelLabel?: string;
    actionLabel?: string;
    showCancelBtn?: boolean;
    showActionBtn?: boolean;
    showHeaderDivider?: boolean;
    showFooterDivider?: boolean;
    showLeadingIcon?: boolean;
    showExtraIcon?: boolean;
    class?: string;
  }>(),
  {
    size: 'sm',
    showFooter: false,
    cancelLabel: 'Cancel',
    actionLabel: 'Action',
    showCancelBtn: true,
    showActionBtn: true,
    showHeaderDivider: false,
    showFooterDivider: false,
    showLeadingIcon: false,
    showExtraIcon: false,
    class: '',
  },
);

defineEmits<{ close: []; cancel: []; action: [] }>();

const headerSize = computed(() => SIZE_HEADER[props.size]);

// NOTE: width below has no matching --sol-* token (component-level size
// variant defined directly in the React source) — ported verbatim.
const rootStyle = computed(() => ({
  width: SIZE_WIDTH[props.size],
  boxShadow: 'var(--sol-shadow-light)',
}));
</script>

<template>
  <div
    :class="[
      'flex flex-col h-full bg-surface-container-highest text-element-primary overflow-hidden text-left',
      props.class,
    ]"
    :style="rootStyle"
  >
    <!-- overlay_header_modal -->
    <OverlayHeaderModal
      :size="headerSize"
      align="left"
      type="web"
      :show-divider="showHeaderDivider"
      :show-leading-icon="showLeadingIcon"
      :show-extra-icon="showExtraIcon"
      @close="$emit('close')"
    >
      <template #title><slot name="title" /></template>
      <template v-if="$slots.leadingIcon" #leadingIcon><slot name="leadingIcon" /></template>
      <template v-if="$slots.extraIcon" #extraIcon><slot name="extraIcon" /></template>
    </OverlayHeaderModal>

    <!-- slot -->
    <div
      class="flex flex-1 flex-col overflow-y-auto w-full text-left"
      style="padding: var(--sol-spacing-16) var(--sol-spacing-24)"
    >
      <slot />
    </div>

    <!-- overlay_footer_modal -->
    <OverlayFooterModal
      v-if="showFooter"
      :size="headerSize"
      align="right"
      type="web"
      :cancel-label="cancelLabel"
      :action-label="actionLabel"
      :show-cancel-btn="showCancelBtn"
      :show-action-btn="showActionBtn"
      :show-divider="showFooterDivider"
      @cancel="$emit('cancel')"
      @action="$emit('action')"
    />
  </div>
</template>

// src/components/Sidesheet/Sidesheet.tsx
import type { ReactNode } from 'react';
import { OverlayHeaderModal } from '../Modal/OverlayHeaderModal';
import { OverlayFooterModal } from '../Modal/OverlayFooterModal';
import type { OverlayHeaderModalSize } from '../Modal/OverlayHeaderModal';

export type SidesheetSize = 'sm' | 'md';

export type SidesheetProps = {
  title: ReactNode;
  children?: ReactNode;
  size?: SidesheetSize;
  showFooter?: boolean;
  cancelLabel?: string;
  actionLabel?: string;
  showCancelBtn?: boolean;
  showActionBtn?: boolean;
  showHeaderDivider?: boolean;
  showFooterDivider?: boolean;
  showLeadingIcon?: boolean;
  leadingIcon?: ReactNode;
  showExtraIcon?: boolean;
  extraIcon?: ReactNode;
  onClose?: () => void;
  onCancel?: () => void;
  onAction?: () => void;
  className?: string;
};

const SIZE_WIDTH: Record<SidesheetSize, number> = {
  sm: 360,
  md: 480,
};

const SIZE_HEADER: Record<SidesheetSize, OverlayHeaderModalSize> = {
  sm: 'sm',
  md: 'md',
};

export function Sidesheet({
  title,
  children,
  size = 'sm',
  showFooter = false,
  cancelLabel = 'Cancel',
  actionLabel = 'Action',
  showCancelBtn = true,
  showActionBtn = true,
  showHeaderDivider = false,
  showFooterDivider = false,
  showLeadingIcon = false,
  leadingIcon,
  showExtraIcon = false,
  extraIcon,
  onClose,
  onCancel,
  onAction,
  className = '',
}: SidesheetProps) {
  const headerSize = SIZE_HEADER[size];

  return (
    <div
      className={`flex flex-col h-full bg-surface-container-highest text-element-primary overflow-hidden ${className}`}
      style={{
        width: SIZE_WIDTH[size],
        boxShadow: 'var(--sol-shadow-light)',
      }}
    >
      {/* overlay_header_modal */}
      <OverlayHeaderModal
        title={title}
        size={headerSize}
        align="left"
        type="web"
        showDivider={showHeaderDivider}
        showLeadingIcon={showLeadingIcon}
        leadingIcon={leadingIcon}
        showExtraIcon={showExtraIcon}
        extraIcon={extraIcon}
        onClose={onClose}
      />

      {/* slot */}
      <div
        className="flex flex-1 flex-col overflow-y-auto w-full"
        style={{ padding: 'var(--sol-spacing-16) var(--sol-spacing-24)' }}
      >
        {children}
      </div>

      {/* overlay_footer_modal */}
      {showFooter && (
        <OverlayFooterModal
          size={headerSize}
          align="right"
          type="web"
          cancelLabel={cancelLabel}
          actionLabel={actionLabel}
          showCancelBtn={showCancelBtn}
          showActionBtn={showActionBtn}
          showDivider={showFooterDivider}
          onCancel={onCancel}
          onAction={onAction}
        />
      )}
    </div>
  );
}
