// src/components/TextHelper/TextHelper.tsx
export type TextHelperType = 'enabled' | 'error';

export type TextHelperProps = {
  helperText: string;
  type?: TextHelperType;
  id?: string;
};

export function TextHelper({ helperText, type = 'enabled', id }: TextHelperProps) {
  return (
    <p
      id={id}
      className={`mt-2 text-text-xs leading-text-xs font-regular ${
        type === 'error' ? 'text-error-dim' : 'text-element-tertiary'
      }`}
    >
      {helperText}
    </p>
  );
}

// src-vue/components/TextHelper/TextHelper.vue
<script lang="ts">
export type TextHelperType = 'enabled' | 'error';
</script>

<script setup lang="ts">
import { computed } from 'vue';

const props = withDefaults(
  defineProps<{
    helperText: string;
    type?: TextHelperType;
    id?: string;
  }>(),
  {
    type: 'enabled',
  },
);

const rootClass = computed(() => [
  'mt-2 text-left text-text-xs leading-text-xs font-regular',
  props.type === 'error' ? 'text-error-dim' : 'text-element-tertiary',
]);
</script>

<template>
  <p :id="id" :class="rootClass">{{ helperText }}</p>
</template>
