// src/components/FloatingToolbar/ToolbarVertical.tsx
import type { ReactNode } from 'react';
import { ToolbarZoom } from './ToolbarZoom';

// ── Types ────────────────────────────────────────────────────────────────────

export type ToolbarVerticalProps = {
  children?: ReactNode;
  onZoomIn?: () => void;
  onZoomOut?: () => void;
  disabledIn?: boolean;
  disabledOut?: boolean;
  className?: string;
};

// ── ToolbarVertical ───────────────────────────────────────────────────────────

export function ToolbarVertical({
  children,
  onZoomIn,
  onZoomOut,
  disabledIn = false,
  disabledOut = false,
  className = '',
}: ToolbarVerticalProps) {
  return (
    <div className={`flex flex-col items-start gap-2 ${className}`}>
      {children}
      <ToolbarZoom
        onZoomIn={onZoomIn}
        onZoomOut={onZoomOut}
        disabledIn={disabledIn}
        disabledOut={disabledOut}
      />
    </div>
  );
}

// src-vue/components/FloatingToolbar/ToolbarVertical.vue
<script setup lang="ts">
import ToolbarZoom from './ToolbarZoom.vue';

withDefaults(
  defineProps<{
    disabledIn?: boolean;
    disabledOut?: boolean;
  }>(),
  {
    disabledIn: false,
    disabledOut: false,
  },
);

const emit = defineEmits<{
  zoomIn: [];
  zoomOut: [];
}>();
</script>

<template>
  <div class="flex flex-col items-start gap-2">
    <slot />
    <ToolbarZoom
      :disabled-in="disabledIn"
      :disabled-out="disabledOut"
      @zoom-in="emit('zoomIn')"
      @zoom-out="emit('zoomOut')"
    />
  </div>
</template>
