// src/components/FloatingToolbar/ToolbarZoomItem.tsx
import type { ReactNode } from 'react';
import { IcPlus } from '../Icon/IcPlus';

// ── Types ────────────────────────────────────────────────────────────────────

export type ToolbarZoomItemType = 'icon' | 'value';
export type ToolbarZoomItemState = 'enabled' | 'disabled';

export type ToolbarZoomItemProps = {
  type?: ToolbarZoomItemType;
  state?: ToolbarZoomItemState;
  icon?: ReactNode;
  value?: string;
  onClick?: () => void;
  className?: string;
};

// ── Style helpers ─────────────────────────────────────────────────────────────

function getContainerCls(state: ToolbarZoomItemState): string {
  if (state === 'disabled') return 'cursor-not-allowed';
  return '';
}

// ── ToolbarZoomItem ───────────────────────────────────────────────────────────

export function ToolbarZoomItem({
  type = 'icon',
  state = 'enabled',
  icon,
  value = '100%',
  onClick,
  className = '',
}: ToolbarZoomItemProps) {
  const isDisabled = state === 'disabled';
  const isIcon = type === 'icon';
  const contentColorCls = isDisabled ? 'text-element-disabled' : 'text-element-secondary';

  return (
    <button
      type="button"
      disabled={isDisabled}
      onClick={onClick}
      className={`group relative flex size-9 shrink-0 items-center justify-center overflow-hidden rounded-2 focus-visible:outline-none ${getContainerCls(state)} ${className}`}
    >
      {!isDisabled && (
        <span className="absolute inset-0.5 rounded-2 group-hover:bg-interaction-neutral-hover group-active:bg-interaction-neutral-pressed" />
      )}

      {isIcon ? (
        <span className={`relative z-10 flex size-5 shrink-0 items-center justify-center ${contentColorCls}`}>
          {icon ?? <IcPlus size={20} />}
        </span>
      ) : (
        <>
          <span className={`relative z-10 text-text-xxs leading-text-xxs font-regular text-center ${contentColorCls}`}>
            {value}
          </span>
          <span className="absolute bottom-0 left-1 right-1 h-px rounded-2 bg-border-solid" />
        </>
      )}
    </button>
  );
}

// src-vue/components/FloatingToolbar/ToolbarZoomItem.vue
<script lang="ts">
export type ToolbarZoomItemType = 'icon' | 'value';
export type ToolbarZoomItemState = 'enabled' | 'disabled';
</script>

<script setup lang="ts">
import { computed } from 'vue';
import IcPlus from '../Icon/IcPlus.vue';

const props = withDefaults(
  defineProps<{
    type?: ToolbarZoomItemType;
    state?: ToolbarZoomItemState;
    value?: string;
  }>(),
  {
    type: 'icon',
    state: 'enabled',
    value: '100%',
  },
);

defineEmits<{ click: [] }>();

const isDisabled = computed(() => props.state === 'disabled');
const isIcon = computed(() => props.type === 'icon');
const contentColorCls = computed(() => (isDisabled.value ? 'text-element-disabled' : 'text-element-secondary'));
const containerCls = computed(() => (isDisabled.value ? 'cursor-not-allowed' : ''));
</script>

<template>
  <button
    type="button"
    :disabled="isDisabled"
    :class="`group relative flex size-9 shrink-0 items-center justify-center overflow-hidden rounded-2 focus-visible:outline-none ${containerCls}`"
    @click="!isDisabled && $emit('click')"
  >
    <span v-if="!isDisabled" class="absolute inset-0.5 rounded-2 group-hover:bg-interaction-neutral-hover group-active:bg-interaction-neutral-pressed" />

    <span v-if="isIcon" :class="`relative z-10 flex size-5 shrink-0 items-center justify-center ${contentColorCls}`">
      <slot name="icon">
        <IcPlus :size="20" />
      </slot>
    </span>
    <template v-else>
      <span :class="`relative z-10 text-text-xxs leading-text-xxs font-regular text-center ${contentColorCls}`">
        {{ value }}
      </span>
      <span class="absolute bottom-0 left-1 right-1 h-px rounded-2 bg-border-solid" />
    </template>
  </button>
</template>
