// src/components/Select/Select.tsx
/**
 * Select / MultiSelect
 *
 * Figma: Select_field (YqKny45xSmjr76WGIXeL7P)
 *   - Trigger:      node 5732-79784
 *   - Dropdown:     node 13579-132834  (Select_field_dropdown)
 *   - text_label:   node 13579-132833 / 13706-121864
 *   - text_helper:  node 13569-87212
 */
import { useState, useRef, useEffect, useLayoutEffect } from 'react';
import { TextLabel } from '../TextLabel/TextLabel';
import { TextHelper } from '../TextHelper/TextHelper';
import Dropdown, { DropdownItem } from '../Dropdown/Dropdown';

// ─── Types ────────────────────────────────────────────────────────────────────

export type SelectOption = {
  value: string;
  label: string;
};

export type SelectState = 'default' | 'error' | 'disabled' | 'readonly';
export type SelectSize = 'sm' | 'md';

// ─── Size config ──────────────────────────────────────────────────────────────

const sizeConfig = {
  sm: { triggerHeight: 'h-[30px]', minTriggerHeight: 'min-h-[30px]' },
  md: { triggerHeight: 'h-9',     minTriggerHeight: 'min-h-9' },
} satisfies Record<SelectSize, { triggerHeight: string; minTriggerHeight: string }>;

// ─── Icons ────────────────────────────────────────────────────────────────────

function IcChevronDown() {
  return (
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <path
        d="M18.5303 9.53027L12.5303 15.5303C12.2374 15.8232 11.7626 15.8232 11.4697 15.5303L5.46973 9.53027L6.53027 8.46973L12 13.9395L17.4697 8.46973L18.5303 9.53027Z"
        fill="currentColor"
      />
    </svg>
  );
}

function IcChevronUp() {
  return (
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <path
        d="M18.5303 9.53027L12.5303 15.5303C12.2374 15.8232 11.7626 15.8232 11.4697 15.5303L5.46973 9.53027L6.53027 8.46973L12 13.9395L17.4697 8.46973L18.5303 9.53027Z"
        fill="currentColor"
        transform="rotate(180 12 12)"
      />
    </svg>
  );
}

function IcChipClose() {
  return (
    <svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true">
      <path d="M10.5 3.5L3.5 10.5M3.5 3.5L10.5 10.5" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" />
    </svg>
  );
}

function IcClear() {
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
      <path d="M12 4L4 12M4 4L12 12" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
    </svg>
  );
}

// ─── Shared Helpers ───────────────────────────────────────────────────────────

function getTriggerBorderClass(state: SelectState, isOpen: boolean) {
  if (state === 'disabled') return 'border-border-normal';
  if (state === 'error') {
    return isOpen
      ? 'border-error-dim shadow-[0_0_0_2px_var(--color-error-dim)]'
      : 'border-error-dim';
  }
  if (state === 'readonly') return 'border-border-normal';
  return isOpen
    ? 'border-border-normal shadow-[0_0_0_2px_var(--color-primary)]'
    : 'border-border-normal';
}


// ─── Select_field_dropdown (node 13579-132834) ────────────────────────────────

// ─── Select (Single) ──────────────────────────────────────────────────────────

export type SelectProps = {
  options: SelectOption[];
  value?: string;
  defaultValue?: string;
  onChange?: (value: string) => void;
  placeholder?: string;
  label?: string;
  helperText?: string;
  state?: SelectState;
  size?: SelectSize;
  required?: boolean;
  className?: string;
};

export function Select({
  options,
  value: controlledValue,
  defaultValue = '',
  onChange,
  placeholder = 'placeholder',
  label,
  helperText,
  state = 'default',
  size = 'md',
  required = false,
  className = '',
}: SelectProps) {
  const [internalValue, setInternalValue] = useState(defaultValue);
  const [isOpen, setIsOpen] = useState(false);
  const containerRef = useRef<HTMLDivElement>(null);

  const value = controlledValue !== undefined ? controlledValue : internalValue;
  const isDisabled = state === 'disabled';
  const isReadonly = state === 'readonly';
  const selectedLabel = options.find((o) => o.value === value)?.label;
  const { triggerHeight } = sizeConfig[size];

  useEffect(() => {
    function handleClickOutside(e: MouseEvent) {
      if (containerRef.current && !containerRef.current.contains(e.target as Node)) {
        setIsOpen(false);
      }
    }
    if (isOpen) document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, [isOpen]);

  function handleSelect(option: SelectOption) {
    if (controlledValue === undefined) setInternalValue(option.value);
    onChange?.(option.value);
    setIsOpen(false);
  }

  function handleKeyDown(e: React.KeyboardEvent) {
    if (isDisabled || isReadonly) return;
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      setIsOpen((v) => !v);
    }
    if (e.key === 'Escape') setIsOpen(false);
  }

  const bgClass = isDisabled
    ? 'bg-fill-disabled cursor-not-allowed'
    : isReadonly
    ? 'bg-surface-container cursor-default'
    : isOpen
    ? 'bg-surface cursor-pointer'
    : 'bg-surface-container cursor-pointer hover:bg-interaction-neutral-hover';

  const borderClass = getTriggerBorderClass(state, isOpen);

  return (
    <div className={`relative flex flex-col items-start ${className}`} ref={containerRef}>
      {label && <TextLabel label={label} required={required} size={size} />}

      <button
        type="button"
        className={`relative flex ${triggerHeight} w-full items-center gap-1 overflow-hidden rounded-4 border pt-sol-8 pb-sol-8 pl-sol-12 pr-sol-8 focus:outline-none ${bgClass} ${borderClass}`}
        onClick={() => {
          if (!isDisabled && !isReadonly) setIsOpen((v) => !v);
        }}
        onKeyDown={handleKeyDown}
        disabled={isDisabled}
        aria-haspopup="listbox"
        aria-expanded={isOpen}
      >
        <span
          className={`flex-1 min-w-0 truncate text-left text-text-sm leading-text-sm-compact font-regular ${
            selectedLabel
              ? isDisabled
                ? 'text-element-disabled'
                : 'text-element-primary'
              : isDisabled
              ? 'text-element-disabled'
              : 'text-element-quaternary'
          }`}
        >
          {selectedLabel ?? placeholder}
        </span>
        <span
          className={`flex shrink-0 size-4 items-center justify-center ${
            isDisabled ? 'text-element-disabled' : 'text-element-quaternary'
          }`}
        >
          {isOpen ? <IcChevronUp /> : <IcChevronDown />}
        </span>
      </button>

      {isOpen && (
        <Dropdown compact={false} className="absolute left-0 right-0 top-full z-50 mt-1">
          {options.map((option) => (
            <DropdownItem
              key={option.value}
              label={option.label}
              selected={value === option.value}
              onClick={() => handleSelect(option)}
            />
          ))}
        </Dropdown>
      )}

      {helperText && (
        <TextHelper helperText={helperText} type={state === 'error' ? 'error' : 'enabled'} />
      )}
    </div>
  );
}

// ─── MultiSelect ──────────────────────────────────────────────────────────────

export type MultiSelectProps = {
  options: SelectOption[];
  value?: string[];
  defaultValue?: string[];
  onChange?: (value: string[]) => void;
  placeholder?: string;
  label?: string;
  helperText?: string;
  state?: SelectState;
  size?: SelectSize;
  required?: boolean;
};

export function MultiSelect({
  options,
  value: controlledValue,
  defaultValue = [],
  onChange,
  placeholder = 'placeholder',
  label,
  helperText,
  state = 'default',
  size = 'md',
  required = false,
}: MultiSelectProps) {
  const [internalValue, setInternalValue] = useState<string[]>(defaultValue);
  const [isOpen, setIsOpen] = useState(false);
  const containerRef = useRef<HTMLDivElement>(null);

  const value = controlledValue !== undefined ? controlledValue : internalValue;
  const isDisabled = state === 'disabled';
  const isReadonly = state === 'readonly';
  const { minTriggerHeight } = sizeConfig[size];

  useEffect(() => {
    function handleClickOutside(e: MouseEvent) {
      if (containerRef.current && !containerRef.current.contains(e.target as Node)) {
        setIsOpen(false);
      }
    }
    if (isOpen) document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, [isOpen]);

  function handleSelect(option: SelectOption) {
    const next = value.includes(option.value)
      ? value.filter((v) => v !== option.value)
      : [...value, option.value];
    if (controlledValue === undefined) setInternalValue(next);
    onChange?.(next);
  }

  function handleRemoveChip(val: string, e: React.MouseEvent) {
    e.stopPropagation();
    const next = value.filter((v) => v !== val);
    if (controlledValue === undefined) setInternalValue(next);
    onChange?.(next);
  }

  function handleClearAll(e: React.MouseEvent) {
    e.stopPropagation();
    if (controlledValue === undefined) setInternalValue([]);
    onChange?.([]);
  }

  const hasValues = value.length > 0;

  // +N more 측정: 칩 컨테이너에서 두 번째 행 이상으로 밀린 칩 수 계산
  const chipContainerRef = useRef<HTMLDivElement>(null);
  const [hiddenCount, setHiddenCount] = useState(0);

  useLayoutEffect(() => {
    const container = chipContainerRef.current;
    if (!container || value.length === 0) {
      setHiddenCount(0);
      return;
    }
    const chips = Array.from(container.children) as HTMLElement[];
    if (chips.length === 0) return;
    const firstRowTop = chips[0].offsetTop;
    setHiddenCount(chips.filter((c) => c.offsetTop > firstRowTop).length);
  }, [value]);

  const bgClass = isDisabled
    ? 'bg-fill-disabled cursor-not-allowed'
    : isReadonly
    ? 'bg-surface-container cursor-default'
    : isOpen
    ? 'bg-surface cursor-pointer'
    : 'bg-surface-container cursor-pointer hover:bg-interaction-neutral-hover';

  const borderClass = getTriggerBorderClass(state, isOpen);

  return (
    <div className="relative flex flex-col items-start" ref={containerRef}>
      {label && <TextLabel label={label} required={required} size={size} />}

      <div
        role="combobox"
        aria-expanded={isOpen}
        aria-haspopup="listbox"
        onClick={() => {
          if (!isDisabled && !isReadonly) setIsOpen((v) => !v);
        }}
        className={`relative flex ${minTriggerHeight} w-full items-start gap-1 overflow-hidden rounded-4 border pt-sol-8 pb-sol-8 pl-sol-12 pr-sol-8 ${bgClass} ${borderClass}`}
      >
        {/* Chips + placeholder */}
        <div className="flex flex-1 min-w-0 flex-col gap-1 overflow-hidden">
          {hasValues ? (
            <>
              {/* 단일 행 칩 영역: 넘치는 칩은 overflow-hidden으로 숨김 */}
              <div
                ref={chipContainerRef}
                className="flex flex-wrap gap-1 overflow-hidden max-h-5"
              >
                {value.map((v) => {
                  const opt = options.find((o) => o.value === v);
                  if (!opt) return null;
                  return (
                    <span
                      key={v}
                      className="inline-flex h-5 shrink-0 items-center gap-0.5 rounded-2 border border-border-normal bg-selected-container px-[5px] py-[3px]"
                    >
                      <span className="text-text-xs leading-text-xs font-regular text-element-brand-variant">
                        {opt.label}
                      </span>
                      {!isDisabled && !isReadonly && (
                        <button
                          type="button"
                          onClick={(e) => handleRemoveChip(v, e)}
                          className="flex shrink-0 items-center justify-center text-element-brand-variant focus:outline-none"
                          aria-label={`Remove ${opt.label}`}
                        >
                          <IcChipClose />
                        </button>
                      )}
                    </span>
                  );
                })}
              </div>
              {/* +N more */}
              {hiddenCount > 0 && (
                <span className="text-text-xs leading-text-xs font-regular text-element-tertiary">
                  +{hiddenCount} more
                </span>
              )}
            </>
          ) : (
            <span
              className={`text-text-sm leading-text-sm-compact font-regular ${
                isDisabled ? 'text-element-disabled' : 'text-element-quaternary'
              }`}
            >
              {placeholder}
            </span>
          )}
        </div>

        {/* Right icons */}
        <div className="flex shrink-0 items-center gap-2">
          {hasValues && !isDisabled && !isReadonly && (
            <button
              type="button"
              onClick={handleClearAll}
              className="flex size-4 items-center justify-center text-element-quaternary focus:outline-none"
              aria-label="Clear all"
            >
              <IcClear />
            </button>
          )}
          <span
            className={`flex size-4 items-center justify-center ${
              isDisabled ? 'text-element-disabled' : 'text-element-quaternary'
            }`}
          >
            {isOpen ? <IcChevronUp /> : <IcChevronDown />}
          </span>
        </div>
      </div>

      {isOpen && (
        <Dropdown compact={false} className="absolute left-0 right-0 top-full z-50 mt-1">
          {options.map((option) => (
            <DropdownItem
              key={option.value}
              label={option.label}
              selected={value.includes(option.value)}
              type="checkbox"
              onClick={() => handleSelect(option)}
            />
          ))}
        </Dropdown>
      )}

      {helperText && (
        <TextHelper helperText={helperText} type={state === 'error' ? 'error' : 'enabled'} />
      )}
    </div>
  );
}

// src-vue/components/Select/Select.vue
<!--
  Select — single-value select field

  React: src/components/Select/Select.tsx (Select)
  React 원본은 useState(isOpen) + mousedown 클릭아웃사이드 + Enter/Space/Escape
  keydown을 수작업으로 구현했다. Vue 포팅에서는 이를 Headless UI Vue의
  Listbox/ListboxButton/ListboxOptions/ListboxOption으로 대체한다:
  open 상태, 클릭아웃사이드, 키보드 내비게이션(Home/End/화살표/타이핑 검색 포함),
  ARIA(role/aria-haspopup/aria-expanded/aria-selected 등)가 모두 Headless UI에서
  무료로 제공된다.

  Controlled value 컨벤션: TextInput.vue와 동일하게 `modelValue`/`update:modelValue`
  + `defaultValue`(비제어 시 초기값) 조합을 사용한다 (React의
  value/defaultValue/onChange 패턴을 그대로 미러링).

  패널(ListboxOptions) 클래스는 Dropdown.vue의 컨테이너 클래스를 그대로 재사용하고,
  옵션(ListboxOption)은 `as="template"`으로 렌더링해 DropdownItem 컴포넌트를 그대로
  감싸서 사용한다 — Headless UI가 클릭/키보드/ARIA props를 DropdownItem의 루트
  <button>에 자동으로 병합(fallthrough)해주므로 별도 어댑터 코드 없이 픽셀이
  동일하게 유지된다.
-->
<script lang="ts">
export type SelectOption = {
  value: string;
  label: string;
};

export type SelectState = 'default' | 'error' | 'disabled' | 'readonly';
export type SelectSize = 'sm' | 'md';
</script>

<script setup lang="ts">
import { computed, ref } from 'vue';
import { Listbox, ListboxButton, ListboxOptions, ListboxOption } from '@headlessui/vue';
import TextLabel from '../TextLabel/TextLabel.vue';
import TextHelper from '../TextHelper/TextHelper.vue';
import DropdownItem from '../Dropdown/DropdownItem.vue';

const props = withDefaults(
  defineProps<{
    options: SelectOption[];
    modelValue?: string;
    defaultValue?: string;
    placeholder?: string;
    label?: string;
    helperText?: string;
    state?: SelectState;
    size?: SelectSize;
    required?: boolean;
    class?: string;
  }>(),
  {
    defaultValue: '',
    placeholder: 'placeholder',
    state: 'default',
    size: 'md',
    required: false,
    class: '',
  },
);

const emit = defineEmits<{
  'update:modelValue': [value: string];
}>();

const internalValue = ref(props.defaultValue);

const value = computed(() =>
  props.modelValue !== undefined ? props.modelValue : internalValue.value,
);
const isDisabled = computed(() => props.state === 'disabled');
const isReadonly = computed(() => props.state === 'readonly');
// NOTE: readonly는 원본에서 포커스는 가능하되 클릭/키다운 핸들러 내부에서
// open을 막는 방식이었다. Headless UI의 Listbox disabled는 포커스까지 막는
// 단일 스위치라 완전히 동일하진 않지만, "패널이 열리지 않는다"는 핵심 동작은
// disabled와 readonly 모두 :disabled="isDisabled || isReadonly"로 재현했다.
const isInteractionDisabled = computed(() => isDisabled.value || isReadonly.value);
const selectedLabel = computed(
  () => props.options.find((o) => o.value === value.value)?.label,
);

const TRIGGER_HEIGHT: Record<SelectSize, string> = { sm: 'h-[30px]', md: 'h-9' };

function handleChange(next: string) {
  if (props.modelValue === undefined) internalValue.value = next;
  emit('update:modelValue', next);
}

function getTriggerBorderClass(open: boolean) {
  if (props.state === 'disabled') return 'border-border-normal';
  if (props.state === 'error') {
    return open
      ? 'border-error-dim shadow-[0_0_0_2px_var(--color-error-dim)]'
      : 'border-error-dim';
  }
  if (props.state === 'readonly') return 'border-border-normal';
  return open
    ? 'border-border-normal shadow-[0_0_0_2px_var(--color-primary)]'
    : 'border-border-normal';
}

function getBgClass(open: boolean) {
  if (isDisabled.value) return 'bg-fill-disabled cursor-not-allowed';
  if (isReadonly.value) return 'bg-surface-container cursor-default';
  if (open) return 'bg-surface cursor-pointer';
  return 'bg-surface-container cursor-pointer hover:bg-interaction-neutral-hover';
}
</script>

<template>
  <Listbox
    as="div"
    :model-value="value"
    :disabled="isInteractionDisabled"
    :class="`relative flex flex-col items-start ${props.class}`"
    @update:model-value="handleChange"
    v-slot="{ open }"
  >
    <TextLabel v-if="label" :label="label" :required="required" :size="size" />

    <ListboxButton
      :class="[
        'relative flex w-full items-center gap-1 overflow-hidden rounded-4 border pt-sol-8 pb-sol-8 pl-sol-12 pr-sol-8 focus:outline-none',
        TRIGGER_HEIGHT[size],
        getBgClass(open),
        getTriggerBorderClass(open),
      ]"
    >
      <span
        :class="[
          'flex-1 min-w-0 truncate text-left text-text-sm leading-text-sm-compact font-regular',
          selectedLabel
            ? (isDisabled ? 'text-element-disabled' : 'text-element-primary')
            : (isDisabled ? 'text-element-disabled' : 'text-element-quaternary'),
        ]"
      >
        {{ selectedLabel ?? placeholder }}
      </span>
      <span
        :class="[
          'flex shrink-0 size-4 items-center justify-center',
          isDisabled ? 'text-element-disabled' : 'text-element-quaternary',
        ]"
      >
        <svg v-if="open" width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true">
          <path
            d="M18.5303 9.53027L12.5303 15.5303C12.2374 15.8232 11.7626 15.8232 11.4697 15.5303L5.46973 9.53027L6.53027 8.46973L12 13.9395L17.4697 8.46973L18.5303 9.53027Z"
            fill="currentColor"
            transform="rotate(180 12 12)"
          />
        </svg>
        <svg v-else width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true">
          <path
            d="M18.5303 9.53027L12.5303 15.5303C12.2374 15.8232 11.7626 15.8232 11.4697 15.5303L5.46973 9.53027L6.53027 8.46973L12 13.9395L17.4697 8.46973L18.5303 9.53027Z"
            fill="currentColor"
          />
        </svg>
      </span>
    </ListboxButton>

    <ListboxOptions
      as="div"
      class="absolute left-0 right-0 top-full z-50 mt-1 min-w-40 overflow-hidden rounded-4 bg-surface-container-high p-1 shadow-normal"
    >
      <div class="overflow-y-auto max-h-80">
        <ListboxOption
          v-for="option in options"
          :key="option.value"
          :value="option.value"
          as="template"
          v-slot="{ selected }"
        >
          <DropdownItem :label="option.label" :selected="selected" />
        </ListboxOption>
      </div>
    </ListboxOptions>

    <TextHelper
      v-if="helperText"
      :helper-text="helperText"
      :type="state === 'error' ? 'error' : 'enabled'"
    />
  </Listbox>
</template>
