// src/components/StructuredList/StructuredListGrid.tsx
import { Fragment, type CSSProperties } from 'react';
import { StructuredListBodyCell, type StructuredListBodyCellProps } from './StructuredListBodyCell';
import { StructuredListSelectCell } from './StructuredListSelectCell';

// ── Types ────────────────────────────────────────────────────────────────────

export type StructuredListGridType = 'column' | 'row';

export type StructuredListGridProps = {
  type?: StructuredListGridType;
  showDivider?: boolean;
  showSelectCell?: boolean;
  selectCellChecked?: boolean;
  condensed?: boolean;
  onSelectChange?: (checked: boolean) => void;
  cells: StructuredListBodyCellProps[];
  className?: string;
  style?: CSSProperties;
};

// ── StructuredListGrid ───────────────────────────────────────────────────────

export function StructuredListGrid({
  type = 'column',
  showDivider = true,
  showSelectCell = false,
  selectCellChecked = false,
  condensed = false,
  onSelectChange,
  cells,
  className = '',
  style,
}: StructuredListGridProps) {
  if (type === 'column') {
    return (
      <div className={`flex items-start overflow-hidden text-left ${className}`} style={style}>
        <div className="flex flex-1 flex-col min-w-0 self-stretch">
          {cells.map((cellProps, i) => (
            <Fragment key={i}>
              <StructuredListBodyCell {...cellProps} />
              {i < cells.length - 1 && (
                <div className="h-px w-full shrink-0 bg-border-solid-variant" />
              )}
            </Fragment>
          ))}
        </div>

        {showDivider && (
          <div className="w-px self-stretch shrink-0 bg-border-solid-variant" />
        )}
      </div>
    );
  }

  // ── Row type ───────────────────────────────────────────────────────────────
  return (
    <div className={`flex flex-col overflow-hidden w-full text-left ${className}`} style={style}>
      <div className="flex items-start w-full shrink-0">
        {showSelectCell && (
          <StructuredListSelectCell
            condensed={condensed}
            checked={selectCellChecked}
            onChange={onSelectChange}
          />
        )}
        <div className="flex flex-1 min-w-0 items-start">
          {cells.map((cellProps, i) => (
            <StructuredListBodyCell
              key={i}
              {...cellProps}
              className={`flex-1${cellProps.className ? ` ${cellProps.className}` : ''}`}
            />
          ))}
        </div>
      </div>

      {showDivider && (
        <div className="h-px w-full shrink-0 bg-border-solid-variant" />
      )}
    </div>
  );
}

// src-vue/components/StructuredList/StructuredListGrid.vue
<script lang="ts">
import type { StyleValue } from 'vue';
import type { StructuredListBodyCellProps } from './StructuredListBodyCell.vue';

export type StructuredListGridType = 'column' | 'row';

export type StructuredListGridProps = {
  type?: StructuredListGridType;
  showDivider?: boolean;
  showSelectCell?: boolean;
  selectCellChecked?: boolean;
  condensed?: boolean;
  // Optional callback form of the `selectChange` emit — Vue treats an
  // `onXxx`-named field as an event-listener attr automatically, so this
  // keeps `StructuredListPattern`'s `grids: StructuredListGridProps[]` array
  // able to wire a per-grid handler the same way the React `onSelectChange`
  // prop did, without StructuredListPattern needing to forward anything.
  onSelectChange?: (checked: boolean) => void;
  cells: StructuredListBodyCellProps[];
  class?: string;
  style?: StyleValue;
};
</script>

<script setup lang="ts">
import StructuredListBodyCell from './StructuredListBodyCell.vue';
import StructuredListSelectCell from './StructuredListSelectCell.vue';

withDefaults(defineProps<Omit<StructuredListGridProps, 'class'>>(), {
  type: 'column',
  showDivider: true,
  showSelectCell: false,
  selectCellChecked: false,
  condensed: false,
});

defineEmits<{ selectChange: [boolean] }>();
</script>

<template>
  <!-- ── Column type ── -->
  <div v-if="type === 'column'" class="flex items-start overflow-hidden text-left" :style="style">
    <div class="flex flex-1 flex-col min-w-0 self-stretch">
      <template v-for="(cellProps, i) in cells" :key="i">
        <StructuredListBodyCell v-bind="cellProps" />
        <div v-if="i < cells.length - 1" class="h-px w-full shrink-0 bg-border-solid-variant" />
      </template>
    </div>

    <div v-if="showDivider" class="w-px self-stretch shrink-0 bg-border-solid-variant" />
  </div>

  <!-- ── Row type ── -->
  <div v-else class="flex flex-col overflow-hidden w-full text-left" :style="style">
    <div class="flex items-start w-full shrink-0">
      <StructuredListSelectCell
        v-if="showSelectCell"
        :condensed="condensed"
        :checked="selectCellChecked"
        @change="$emit('selectChange', $event)"
      />
      <div class="flex flex-1 min-w-0 items-start">
        <StructuredListBodyCell
          v-for="(cellProps, i) in cells"
          :key="i"
          class="flex-1"
          v-bind="cellProps"
        />
      </div>
    </div>

    <div v-if="showDivider" class="h-px w-full shrink-0 bg-border-solid-variant" />
  </div>
</template>
