// src-vue/components/StructuredList/StructuredListPattern.vue
<script lang="ts">
import type { StructuredListGridProps } from './StructuredListGrid.vue';

export type StructuredListPatternOrientation = 'horizontal' | 'vertical';

export type StructuredListPatternProps = {
  orientation?: StructuredListPatternOrientation;
  title?: string;
  showHeader?: boolean;
  grids: StructuredListGridProps[];
  class?: string;
};
</script>

<script setup lang="ts">
import { computed } from 'vue';
import StructuredListGrid from './StructuredListGrid.vue';

const props = withDefaults(defineProps<Omit<StructuredListPatternProps, 'class'>>(), {
  orientation: 'horizontal',
  title: 'Section Header',
  showHeader: true,
});

const isHorizontal = computed(() => props.orientation === 'horizontal');
const headerTextClass = computed(() =>
  isHorizontal.value ? 'text-text-lg leading-text-lg' : 'text-text-md leading-text-md',
);
</script>

<template>
  <div class="flex flex-col items-start w-full text-left">
    <!-- ── Section header ── -->
    <div v-if="showHeader" class="flex flex-col items-start shrink-0 w-full text-left">
      <span :class="[headerTextClass, 'font-semibold text-element-primary whitespace-nowrap text-left']">
        {{ title }}
      </span>
      <div class="shrink-0 w-full h-2" />
    </div>

    <!-- ── Grids ── -->
    <div :class="['flex items-start shrink-0 w-full', isHorizontal ? 'flex-col' : 'flex-row']">
      <StructuredListGrid v-for="(gridProps, i) in grids" :key="i" v-bind="gridProps" />
    </div>
  </div>
</template>

// src/components/StructuredList/StructuredListPattern.tsx
import type { ReactNode } from 'react';
import { StructuredListGrid, type StructuredListGridProps } from './StructuredListGrid';

// ── Types ────────────────────────────────────────────────────────────────────

export type StructuredListPatternOrientation = 'horizontal' | 'vertical';

export type StructuredListPatternProps = {
  orientation?: StructuredListPatternOrientation;
  title?: string;
  showHeader?: boolean;
  grids: StructuredListGridProps[];
  className?: string;
};

// ── SectionHeader ────────────────────────────────────────────────────────────

type SectionHeaderProps = {
  title?: string;
  size?: 'md' | 'sm';
};

function SectionHeader({ title = 'Section Header', size = 'md' }: SectionHeaderProps) {
  const textCls =
    size === 'md'
      ? 'text-text-lg leading-text-lg'
      : 'text-text-md leading-text-md';

  return (
    <div className="flex flex-col items-start shrink-0 w-full">
      <span className={`${textCls} font-semibold text-element-primary whitespace-nowrap`}>
        {title}
      </span>
      <div className="shrink-0 w-full h-2" />
    </div>
  );
}

// ── StructuredListPattern ────────────────────────────────────────────────────

export function StructuredListPattern({
  orientation = 'horizontal',
  title = 'Section Header',
  showHeader = true,
  grids,
  className = '',
}: StructuredListPatternProps) {
  const isHorizontal = orientation === 'horizontal';

  return (
    <div className={`flex flex-col items-start w-full ${className}`}>
      {showHeader && (
        <SectionHeader title={title} size={isHorizontal ? 'md' : 'sm'} />
      )}

      {/* Slot */}
      <div className={`flex ${isHorizontal ? 'flex-col' : 'flex-row'} items-start shrink-0 w-full`}>
        {grids.map((gridProps, i) => (
          <StructuredListGrid key={i} {...gridProps} />
        ))}
      </div>
    </div>
  );
}
