// src-vue/components/StructuredList/StructuredListSelectCell.vue
<script setup lang="ts">
import { computed } from 'vue';

const props = withDefaults(
  defineProps<{
    condensed?: boolean;
    checked?: boolean;
    disabled?: boolean;
  }>(),
  {
    condensed: false,
    checked: false,
    disabled: false,
  },
);

const emit = defineEmits<{ change: [boolean] }>();

function handleClick() {
  if (!props.disabled) emit('change', !props.checked);
}

// ── Classes ──────────────────────────────────────────────────────────────────

const containerClass = computed(() => [
  'flex min-w-8 w-14 shrink-0 flex-col items-center justify-center text-left',
  props.condensed ? 'min-h-8 pt-2 pb-2' : 'min-h-14 pt-4 pb-6',
]);

const buttonClass = computed(() => [
  'group relative flex size-5 shrink-0 items-center justify-center rounded-full text-left',
  'focus:outline-none focus-visible:shadow-[0_0_0_2px_var(--sol-primary)]',
  props.disabled ? 'cursor-not-allowed' : 'cursor-pointer',
]);

const radioCircleClass = computed(() => [
  'absolute inset-[16.67%] flex items-center justify-center rounded-full',
  props.checked
    ? props.disabled
      ? 'bg-fill-disabled'
      : 'bg-tertiary'
    : props.disabled
      ? 'border border-border-disabled bg-surface-container'
      : 'border border-border-normal bg-surface-container',
]);

const innerDotClass = computed(() => [
  'size-1.5 rounded-full',
  props.disabled ? 'bg-element-disabled' : 'bg-element-inverse',
]);
</script>

<template>
  <div :class="containerClass">
    <button
      type="button"
      role="radio"
      :aria-checked="checked"
      :disabled="disabled"
      :class="buttonClass"
      @click="handleClick"
    >
      <!-- Interaction overlay (full 20px area) -->
      <span
        v-if="!disabled"
        aria-hidden="true"
        class="absolute inset-0 rounded-full bg-interaction-neutral-normal group-hover:bg-interaction-neutral-hover group-active:bg-interaction-neutral-pressed"
      />

      <!-- Radio circle (inset ~16.67%) -->
      <span :class="radioCircleClass">
        <!-- Inner dot -->
        <span v-if="checked" :class="innerDotClass" />
      </span>
    </button>
  </div>
</template>

// src/components/StructuredList/StructuredListSelectCell.tsx
// ── Types ────────────────────────────────────────────────────────────────────

export type StructuredListSelectCellProps = {
  condensed?: boolean;
  checked?: boolean;
  disabled?: boolean;
  onChange?: (checked: boolean) => void;
  className?: string;
};

// ── StructuredListSelectCell ─────────────────────────────────────────────────

export function StructuredListSelectCell({
  condensed = false,
  checked = false,
  disabled = false,
  onChange,
  className = '',
}: StructuredListSelectCellProps) {
  const containerStyle = condensed
    ? { minHeight: 32, paddingTop: 8, paddingBottom: 8 }
    : { minHeight: 56, paddingTop: 16, paddingBottom: 24 };

  return (
    <div
      className={`flex flex-col items-center justify-center shrink-0 ${className}`}
      style={{ minWidth: 32, width: 56, ...containerStyle }}
    >
      <button
        type="button"
        role="radio"
        aria-checked={checked}
        disabled={disabled}
        onClick={() => !disabled && onChange?.(!checked)}
        className={`group relative flex items-center justify-center shrink-0 rounded-full focus:outline-none focus-visible:shadow-[0_0_0_2px_var(--sol-primary)] ${disabled ? 'cursor-not-allowed' : 'cursor-pointer'}`}
        style={{ width: 20, height: 20 }}
      >
        {/* Interaction overlay (full 20px area) */}
        {!disabled && (
          <span className="absolute inset-0 rounded-full bg-interaction-neutral-normal group-hover:bg-interaction-neutral-hover group-active:bg-interaction-neutral-pressed" />
        )}

        {/* Radio circle (inset 16.67% → ~13.3px) */}
        <span
          className={`absolute flex items-center justify-center rounded-full ${
            checked
              ? disabled
                ? 'bg-fill-disabled'
                : 'bg-tertiary'
              : disabled
                ? 'border border-border-disabled bg-surface-container'
                : 'border border-border-normal bg-surface-container'
          }`}
          style={{ inset: '16.67%' }}
        >
          {/* Inner dot */}
          {checked && (
            <span
              className={`rounded-full ${disabled ? 'bg-element-disabled' : 'bg-element-inverse'}`}
              style={{ width: 6, height: 6 }}
            />
          )}
        </span>
      </button>
    </div>
  );
}
