// src-vue/components/SegmentedControl/SegmentedControl.vue
<script lang="ts">
export type SegmentedControlItem = {
  label: string;
};

export type SegmentedControlType = 'outlined' | 'solid';
</script>

<script setup lang="ts">
import { ref, computed } from 'vue';

const props = withDefaults(
  defineProps<{
    items: SegmentedControlItem[];
    type?: SegmentedControlType;
    selectedIndex?: number;
    disabled?: boolean;
  }>(),
  {
    type: 'outlined',
    disabled: false,
  },
);

const emit = defineEmits<{ select: [number] }>();

const internalIndex = ref(0);
const activeIndex = computed(() => props.selectedIndex ?? internalIndex.value);
const isSolid = computed(() => props.type === 'solid');

function handleSelect(index: number) {
  if (props.disabled) return;
  emit('select', index);
  if (props.selectedIndex === undefined) {
    internalIndex.value = index;
  }
}

function outlinedRounding(index: number) {
  if (index === 0) return 'rounded-l-4';
  if (index === props.items.length - 1) return 'rounded-r-4';
  return '';
}
</script>

<template>
  <div
    role="tablist"
    :class="`relative flex h-8 w-full items-center overflow-clip rounded-4 text-left ${isSolid ? 'bg-surface-container-low p-[3px]' : ''}`"
  >
    <!-- Outer border (outlined only) -->
    <span
      v-if="!isSolid"
      aria-hidden="true"
      class="pointer-events-none absolute inset-0 rounded-4 border border-border-normal"
    />

    <button
      v-for="(item, index) in items"
      :key="index"
      type="button"
      role="tab"
      :aria-selected="index === activeIndex"
      :disabled="disabled"
      :class="`group relative flex h-full flex-1 items-center justify-center overflow-clip
        ${isSolid ? 'rounded-2' : outlinedRounding(index)}
        ${disabled ? 'cursor-not-allowed' : 'cursor-pointer'}
        focus:outline-none focus-visible:shadow-focus-button-ring`"
      @click="handleSelect(index)"
    >
      <!-- ── Solid active: white bg + shadow ── -->
      <span
        v-if="isSolid && index === activeIndex"
        aria-hidden="true"
        class="pointer-events-none absolute inset-0 rounded-2 bg-secondary shadow-extralight"
      />

      <!-- ── Outlined active: tertiary bg + border ── -->
      <span
        v-if="!isSolid && index === activeIndex"
        aria-hidden="true"
        :class="`pointer-events-none absolute inset-0 bg-tertiary-container border border-tertiary ${outlinedRounding(index)}`"
      />

      <!-- Right divider for inactive outlined segments -->
      <span
        v-if="!isSolid && index !== activeIndex && index !== items.length - 1"
        aria-hidden="true"
        class="pointer-events-none absolute inset-0 border-r border-border-normal"
      />

      <!-- Interaction overlay -->
      <span
        v-if="!disabled"
        aria-hidden="true"
        :class="`pointer-events-none absolute inset-0
          ${isSolid ? 'rounded-2' : outlinedRounding(index)}
          bg-interaction-neutral-normal
          group-hover:bg-interaction-neutral-hover
          group-active:bg-interaction-neutral-pressed`"
      />

      <!-- Label -->
      <span
        :class="`relative whitespace-nowrap text-left font-semibold
          ${isSolid ? 'px-sol-12 text-text-xs leading-text-xs' : 'px-sol-8 text-text-xs leading-text-xs'}
          ${
            isSolid
              ? index === activeIndex
                ? 'text-element-primary'
                : 'text-element-quaternary'
              : index === activeIndex
                ? 'text-element-brand-variant'
                : 'text-element-quaternary'
          }
          ${disabled ? 'opacity-50' : ''}`"
      >
        {{ item.label }}
      </span>
    </button>
  </div>
</template>

// src/components/SegmentedControl/SegmentedControl.tsx
import { useState, useCallback } from 'react';

// ── Types ──────────────────────────────────────────────────────────────────

export type SegmentedControlItem = {
  label: string;
};

export type SegmentedControlType = 'outlined' | 'solid';

export type SegmentedControlProps = {
  items: SegmentedControlItem[];
  type?: SegmentedControlType;
  selectedIndex?: number;
  onSelect?: (index: number) => void;
  disabled?: boolean;
  className?: string;
};

// ── SegmentedControl ───────────────────────────────────────────────────────

export default function SegmentedControl({
  items,
  type = 'outlined',
  selectedIndex: controlledIndex,
  onSelect,
  disabled = false,
  className,
}: SegmentedControlProps) {
  const [internalIndex, setInternalIndex] = useState(0);
  const activeIndex = controlledIndex ?? internalIndex;

  const handleSelect = useCallback(
    (index: number) => {
      if (disabled) return;
      if (onSelect) {
        onSelect(index);
      } else {
        setInternalIndex(index);
      }
    },
    [onSelect, disabled],
  );

  const count = items.length;
  const isSolid = type === 'solid';

  return (
    <div
      role="tablist"
      className={`relative flex h-8 w-full items-center overflow-clip rounded-4
        ${isSolid ? 'bg-surface-container-low p-[3px]' : ''}
        ${className ?? ''}`}
    >
      {/* Outer border (outlined only) */}
      {!isSolid && (
        <span
          aria-hidden="true"
          className="pointer-events-none absolute inset-0 rounded-4 border border-border-normal"
        />
      )}

      {items.map((item, index) => {
        const isActive = index === activeIndex;
        const isFirst = index === 0;
        const isLast = index === count - 1;

        const outlinedRounding = isFirst
          ? 'rounded-l-4'
          : isLast
            ? 'rounded-r-4'
            : '';

        return (
          <button
            key={index}
            type="button"
            role="tab"
            aria-selected={isActive}
            disabled={disabled}
            onClick={() => handleSelect(index)}
            className={`group relative flex h-full flex-1 items-center justify-center overflow-clip
              ${isSolid ? 'rounded-2' : outlinedRounding}
              ${disabled ? 'cursor-not-allowed' : 'cursor-pointer'}
              focus:outline-none focus-visible:shadow-focus-button-ring
            `}
          >
            {/* ── Solid active: white bg + shadow ── */}
            {isSolid && isActive && (
              <span
                aria-hidden="true"
                className="pointer-events-none absolute inset-0 rounded-2 bg-secondary shadow-extralight"
              />
            )}

            {/* ── Outlined active: tertiary bg + border ── */}
            {!isSolid && isActive && (
              <span
                aria-hidden="true"
                className={`pointer-events-none absolute inset-0 bg-tertiary-container border border-tertiary ${outlinedRounding}`}
              />
            )}

            {/* Right divider for inactive outlined segments */}
            {!isSolid && !isActive && !isLast && (
              <span
                aria-hidden="true"
                className="pointer-events-none absolute inset-0 border-r border-border-normal"
              />
            )}

            {/* Interaction overlay */}
            {!disabled && (
              <span
                aria-hidden="true"
                className={`pointer-events-none absolute inset-0
                  ${isSolid ? 'rounded-2' : outlinedRounding}
                  bg-interaction-neutral-normal
                  group-hover:bg-interaction-neutral-hover
                  group-active:bg-interaction-neutral-pressed`}
              />
            )}

            {/* Label */}
            <span
              className={`relative whitespace-nowrap font-semibold
                ${isSolid ? 'px-sol-12 text-text-xs leading-text-xs' : 'px-sol-8 text-text-xs leading-text-xs'}
                ${isSolid
                  ? (isActive ? 'text-element-primary' : 'text-element-quaternary')
                  : (isActive ? 'text-element-brand-variant' : 'text-element-quaternary')
                }
                ${disabled ? 'opacity-50' : ''}
              `}
            >
              {item.label}
            </span>
          </button>
        );
      })}
    </div>
  );
}
