// src/components/TextInput/TextInput.tsx
import { useState, useId, forwardRef } from 'react';
import { TextLabel } from '../TextLabel/TextLabel';
import { TextHelper } from '../TextHelper/TextHelper';
import { IcBlank } from '../Icon/IcBlank';

// ── Types ────────────────────────────────────────────────────────────────────

export type TextInputState = 'default' | 'error' | 'disabled' | 'readonly';
export type TextInputSize = 'sm' | 'md';

export type TextInputProps = {
  value?: string;
  defaultValue?: string;
  onChange?: (value: string) => void;
  onFocus?: (e: React.FocusEvent<HTMLInputElement>) => void;
  onBlur?: (e: React.FocusEvent<HTMLInputElement>) => void;
  placeholder?: string;
  label?: string;
  helperText?: string;
  state?: TextInputState;
  size?: TextInputSize;
  required?: boolean;
  maxLength?: number;
  leadingIcon?: React.ReactNode;
  showLeadingIcon?: boolean;
  trailingIcon?: React.ReactNode;
  showTrailingIcon?: boolean;
  onTrailingIconClick?: () => void;
  showClearButton?: boolean;
  autoFocus?: boolean;
  type?: React.HTMLInputTypeAttribute;
  className?: string;
};

// ── Close icon (filled circle + white ×) ─────────────────────────────────────

function IcClose({ size }: { size: 12 | 14 | 16 }) {
  return (
    <svg width={size} height={size} viewBox="0 0 16 16" fill="none" aria-hidden="true">
      <circle cx="8" cy="8" r="8" fill="currentColor" />
      <path
        d="M10.5 5.5L5.5 10.5M5.5 5.5L10.5 10.5"
        stroke="white"
        strokeWidth="1.4"
        strokeLinecap="round"
      />
    </svg>
  );
}

// ── Style helpers ─────────────────────────────────────────────────────────────

function getWrapperCls(
  state: TextInputState,
  isFocused: boolean,
  size: TextInputSize,
): string {
  const sizeCls = size === 'sm' ? 'h-7.5 px-2.5' : 'h-9 px-3';

  const stateCls = (() => {
    if (state === 'disabled' || state === 'readonly')
      return 'bg-fill-disabled border-border-normal';
    if (state === 'error')
      return isFocused
        ? 'bg-surface-container border-error-dim shadow-[0_0_0_2px_var(--color-error-dim)]'
        : 'bg-surface-container border-error-dim';
    return isFocused
      ? 'bg-surface-container border-border-normal shadow-[0_0_0_2px_var(--color-primary)]'
      : 'bg-surface-container border-border-normal';
  })();

  return `flex items-center gap-1 overflow-hidden rounded-4 border shrink-0 w-full ${sizeCls} ${stateCls}`;
}

function getInputCls(state: TextInputState, size: TextInputSize): string {
  const sizeCls =
    size === 'sm'
      ? 'text-text-xs leading-text-xs'
      : 'text-text-sm leading-text-xs-2line';

  const colorCls =
    state === 'disabled'
      ? 'text-element-disabled placeholder:text-element-disabled cursor-not-allowed'
      : 'text-element-primary placeholder:text-element-quaternary';

  return `min-w-0 flex-1 bg-transparent outline-none font-regular overflow-hidden text-ellipsis whitespace-nowrap ${sizeCls} ${colorCls}`;
}

// ── TextInput ─────────────────────────────────────────────────────────────────

const TextInput = forwardRef<HTMLInputElement, TextInputProps>(
  function TextInput(
    {
      value: controlledValue,
      defaultValue = '',
      onChange,
      onFocus,
      onBlur,
      placeholder = 'Placeholder',
      label,
      helperText,
      state = 'default',
      size = 'md',
      required = false,
      maxLength,
      leadingIcon,
      showLeadingIcon = false,
      trailingIcon,
      showTrailingIcon = false,
      onTrailingIconClick,
      showClearButton = false,
      autoFocus = false,
      type = 'text',
      className,
    },
    ref,
  ) {
    const [internalValue, setInternalValue] = useState(defaultValue);
    const [isFocused, setIsFocused] = useState(false);
    const inputId = useId();

    const value =
      controlledValue !== undefined ? controlledValue : internalValue;
    const isDisabled = state === 'disabled';
    const isReadonly = state === 'readonly';
    const iconSize = size === 'sm' ? 14 : 16;
    const showClear =
      showClearButton && isFocused && value.length > 0 && !isDisabled && !isReadonly;

    function handleChange(e: React.ChangeEvent<HTMLInputElement>) {
      const next = e.target.value;
      if (controlledValue === undefined) setInternalValue(next);
      onChange?.(next);
    }

    function handleFocus(e: React.FocusEvent<HTMLInputElement>) {
      setIsFocused(true);
      onFocus?.(e);
    }

    function handleBlur(e: React.FocusEvent<HTMLInputElement>) {
      setIsFocused(false);
      onBlur?.(e);
    }

    function handleClear() {
      if (controlledValue === undefined) setInternalValue('');
      onChange?.('');
    }

    return (
      <div className={`flex flex-col text-left ${className ?? ''}`}>
        {label && (
          <TextLabel label={label} required={required} size={size} />
        )}

        <div className={getWrapperCls(state, isFocused, size)}>
          {/* Leading icon */}
          {showLeadingIcon && (
            <span
              className={`shrink-0 flex items-center justify-center ${isDisabled ? 'text-element-disabled' : 'text-element-secondary'}`}
              style={{ width: `${iconSize}px`, height: `${iconSize}px` }}
            >
              {leadingIcon ?? <IcBlank size={iconSize as 14 | 16} />}
            </span>
          )}

          {/* Input */}
          <input
            ref={ref}
            id={inputId}
            type={type}
            value={value}
            placeholder={placeholder}
            disabled={isDisabled}
            readOnly={isReadonly}
            required={required}
            maxLength={maxLength}
            autoFocus={autoFocus}
            onChange={handleChange}
            onFocus={handleFocus}
            onBlur={handleBlur}
            aria-invalid={state === 'error' || undefined}
            className={getInputCls(state, size)}
          />

          {/* Clear button — shown when focused and has value */}
          {showClear && (
            <button
              type="button"
              tabIndex={-1}
              onMouseDown={(e) => {
                e.preventDefault();
                handleClear();
              }}
              className="shrink-0 flex items-center justify-center rounded-circle text-element-quaternary hover:text-element-primary focus:outline-none"
              style={{ width: `${iconSize}px`, height: `${iconSize}px` }}
              aria-label="Clear"
            >
              <IcClose size={iconSize as 14 | 16} />
            </button>
          )}

          {/* Trailing icon */}
          {showTrailingIcon && !showClear && (
            <button
              type="button"
              tabIndex={-1}
              onClick={onTrailingIconClick}
              disabled={isDisabled}
              className={`shrink-0 flex items-center justify-center rounded-circle focus:outline-none ${isDisabled ? 'text-element-disabled cursor-not-allowed' : 'text-element-primary'}`}
              style={{ width: `${iconSize}px`, height: `${iconSize}px` }}
            >
              {trailingIcon ?? <IcBlank size={iconSize as 14 | 16} />}
            </button>
          )}
        </div>

        {helperText && (
          <TextHelper
            helperText={helperText}
            type={state === 'error' ? 'error' : 'enabled'}
          />
        )}
      </div>
    );
  },
);

export default TextInput;

// src-vue/components/TextInput/TextInput.vue
<script lang="ts">
export type TextInputState = 'default' | 'error' | 'disabled' | 'readonly';
export type TextInputSize = 'sm' | 'md';
</script>

<script setup lang="ts">
import { computed, ref, useId } from 'vue';
import TextLabel from '../TextLabel/TextLabel.vue';
import TextHelper from '../TextHelper/TextHelper.vue';
import IcResponsive from '../Icon/IcResponsive.vue';

const props = withDefaults(
  defineProps<{
    modelValue?: string;
    defaultValue?: string;
    placeholder?: string;
    label?: string;
    helperText?: string;
    state?: TextInputState;
    size?: TextInputSize;
    required?: boolean;
    maxLength?: number;
    showLeadingIcon?: boolean;
    showTrailingIcon?: boolean;
    showClearButton?: boolean;
    autoFocus?: boolean;
    type?: string;
  }>(),
  {
    defaultValue: '',
    placeholder: 'Placeholder',
    state: 'default',
    size: 'md',
    required: false,
    showLeadingIcon: false,
    showTrailingIcon: false,
    showClearButton: false,
    autoFocus: false,
    type: 'text',
  },
);

const emit = defineEmits<{
  'update:modelValue': [value: string];
  focus: [event: FocusEvent];
  blur: [event: FocusEvent];
  trailingIconClick: [];
}>();

const inputId = useId();
const inputRef = ref<HTMLInputElement | null>(null);
const internalValue = ref(props.defaultValue);
const isFocused = ref(false);

const value = computed(() =>
  props.modelValue !== undefined ? props.modelValue : internalValue.value,
);
const isDisabled = computed(() => props.state === 'disabled');
const isReadonly = computed(() => props.state === 'readonly');
const iconSize = computed<14 | 16>(() => (props.size === 'sm' ? 14 : 16));
const showClear = computed(
  () =>
    props.showClearButton &&
    isFocused.value &&
    value.value.length > 0 &&
    !isDisabled.value &&
    !isReadonly.value,
);

// ── Style helpers ────────────────────────────────────────────────────────

const wrapperClass = computed(() => {
  const sizeCls = props.size === 'sm' ? 'h-7.5 px-2.5' : 'h-9 px-3';

  const stateCls = (() => {
    if (isDisabled.value || isReadonly.value) return 'bg-fill-disabled border-border-normal';
    if (props.state === 'error')
      return isFocused.value
        ? 'bg-surface-container border-error-dim shadow-[0_0_0_2px_var(--color-error-dim)]'
        : 'bg-surface-container border-error-dim';
    return isFocused.value
      ? 'bg-surface-container border-border-normal shadow-[0_0_0_2px_var(--color-primary)]'
      : 'bg-surface-container border-border-normal';
  })();

  return `flex items-center gap-1 overflow-hidden rounded-4 border shrink-0 w-full ${sizeCls} ${stateCls}`;
});

const inputClass = computed(() => {
  const sizeCls =
    props.size === 'sm' ? 'text-text-xs leading-text-xs' : 'text-text-sm leading-text-xs-2line';

  const colorCls = isDisabled.value
    ? 'text-element-disabled placeholder:text-element-disabled cursor-not-allowed'
    : 'text-element-primary placeholder:text-element-quaternary';

  return `min-w-0 flex-1 bg-transparent outline-none font-regular overflow-hidden text-ellipsis whitespace-nowrap ${sizeCls} ${colorCls}`;
});

const leadingIconWrapperClass = computed(() =>
  isDisabled.value ? 'text-element-disabled' : 'text-element-secondary',
);

const trailingIconBtnClass = computed(() => [
  'shrink-0 flex items-center justify-center rounded-circle focus:outline-none',
  isDisabled.value ? 'text-element-disabled cursor-not-allowed' : 'text-element-primary',
]);

// ── Handlers ─────────────────────────────────────────────────────────────

function handleInput(e: Event) {
  const next = (e.target as HTMLInputElement).value;
  if (props.modelValue === undefined) internalValue.value = next;
  emit('update:modelValue', next);
}

function handleFocus(e: FocusEvent) {
  isFocused.value = true;
  emit('focus', e);
}

function handleBlur(e: FocusEvent) {
  isFocused.value = false;
  emit('blur', e);
}

function handleClear() {
  if (props.modelValue === undefined) internalValue.value = '';
  emit('update:modelValue', '');
}

defineExpose({ inputRef });
</script>

<template>
  <div class="flex flex-col text-left">
    <TextLabel v-if="label" :label="label" :required="required" :size="size" />

    <div :class="wrapperClass">
      <!-- Leading icon -->
      <IcResponsive
        v-if="showLeadingIcon"
        :size="iconSize"
        :class="leadingIconWrapperClass"
      >
        <slot name="leadingIcon" />
      </IcResponsive>

      <!-- Input -->
      <input
        ref="inputRef"
        :id="inputId"
        :type="type"
        :value="value"
        :placeholder="placeholder"
        :disabled="isDisabled"
        :readonly="isReadonly"
        :required="required"
        :maxlength="maxLength"
        :autofocus="autoFocus"
        :aria-invalid="state === 'error' ? true : undefined"
        :class="inputClass"
        @input="handleInput"
        @focus="handleFocus"
        @blur="handleBlur"
      />

      <!-- Clear button — shown when focused and has value -->
      <button
        v-if="showClear"
        type="button"
        tabindex="-1"
        class="shrink-0 flex items-center justify-center rounded-circle text-element-quaternary hover:text-element-primary focus:outline-none"
        :class="iconSize === 14 ? 'size-icon-14' : 'size-icon-16'"
        aria-label="Clear"
        @mousedown.prevent="handleClear"
      >
        <svg :width="iconSize" :height="iconSize" viewBox="0 0 16 16" fill="none" aria-hidden="true">
          <circle cx="8" cy="8" r="8" fill="currentColor" />
          <path
            d="M10.5 5.5L5.5 10.5M5.5 5.5L10.5 10.5"
            stroke="white"
            stroke-width="1.4"
            stroke-linecap="round"
          />
        </svg>
      </button>

      <!-- Trailing icon -->
      <button
        v-if="showTrailingIcon && !showClear"
        type="button"
        tabindex="-1"
        :disabled="isDisabled"
        :class="trailingIconBtnClass"
        @click="!isDisabled && emit('trailingIconClick')"
      >
        <IcResponsive :size="iconSize">
          <slot name="trailingIcon" />
        </IcResponsive>
      </button>
    </div>

    <TextHelper
      v-if="helperText"
      :helper-text="helperText"
      :type="state === 'error' ? 'error' : 'enabled'"
    />
  </div>
</template>
